---
# tasks file for ansible-role-firewalld
- name: install firewalld package
  yum:
    name: firewalld
  # latest version was BUG. so dawngraded.
  #  yum:
  #    name: "{{ packages }}"
  #  vars:
  #    packages:
  #      - http://vault.centos.org/7.6.1810/os/x86_64/Packages/firewalld-0.5.3-5.el7.noarch.rpm
  #      - http://vault.centos.org/7.6.1810/os/x86_64/Packages/firewalld-filesystem-0.5.3-5.el7.noarch.rpm
  #      - http://vault.centos.org/7.6.1810/os/x86_64/Packages/python-firewall-0.5.3-5.el7.noarch.rpm

- name: start firewalld service
  service:
    name: firewalld
    state: started
    enabled: yes

- name: detected firewall rules (direct rule)
  command: iptables -L INPUT_direct
  register: firewall_rules
  failed_when: no
  check_mode: no
  changed_when: firewall_rules.rc != 0

- name: set firewall rules (direct rule)
  command: "firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 {{ item }}"
  with_items:
    - '-p tcp --tcp-flags ALL NONE -j DROP'
    - '-p tcp ! --syn -m state --state NEW -j DROP'
    - '-p tcp --tcp-flags ALL ALL -j DROP'
  notify: restart firewalld service
  when: firewall_rules is changed

- name: set firewall rules (ports)
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items: "{{ firewall_enabled_ports }}"
  notify: restart firewalld service

- name: unset firewall default rules
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: disabled
  with_items:
    - ssh
    - dhcpv6-client
  notify: restart firewalld service
