---
# handlers file for ansible-role-firewalld
- name: restart firewalld service
  service:
    name: firewalld
    state: restarted

- name: restart fail2ban service
  service:
    name: fail2ban
    state: restarted
